// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGDZvcdLDnAHuM6dYzkCAwn_x_BECMqnQ',
    appId: '1:681304030968:android:e5d86da58fe0314cfa850d',
    messagingSenderId: '681304030968',
    projectId: 'fitfriends-tracker-app',
    storageBucket: 'fitfriends-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2m8DPzTU2Ic-5DvfKOiwn3j7tmCWsttM',
    appId: '1:681304030968:web:52054b564924d78dfa850d',
    messagingSenderId: '681304030968',
    projectId: 'fitfriends-tracker-app',
    authDomain: 'fitfriends-tracker-app.firebaseapp.com',
    storageBucket: 'fitfriends-tracker-app.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCER2BIuTYxya6ULVwdyYuipRSWgSHHVmQ',
    appId: '1:681304030968:ios:4a4ddd7523bc17cefa850d',
    messagingSenderId: '681304030968',
    projectId: 'fitfriends-tracker-app',
    storageBucket: 'fitfriends-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.fitfriendsTracker',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCER2BIuTYxya6ULVwdyYuipRSWgSHHVmQ',
    appId: '1:681304030968:ios:4a4ddd7523bc17cefa850d',
    messagingSenderId: '681304030968',
    projectId: 'fitfriends-tracker-app',
    storageBucket: 'fitfriends-tracker-app.firebasestorage.app',
    iosBundleId: 'com.example.fitfriendsTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2m8DPzTU2Ic-5DvfKOiwn3j7tmCWsttM',
    appId: '1:681304030968:web:af15639de629fdcdfa850d',
    messagingSenderId: '681304030968',
    projectId: 'fitfriends-tracker-app',
    authDomain: 'fitfriends-tracker-app.firebaseapp.com',
    storageBucket: 'fitfriends-tracker-app.firebasestorage.app',
  );

}